import 'package:get/get.dart';

class LocaleString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    //ENGLISH LANGUAGE
    'en_US':{
      'home':"Home",
      'hello':'Hello',
      'welcome':'Welcome',
      'sign-in':'Sign in to Continue',
      'create-account':'Create Mfunzi Account',
      'sign-up':' Register',
      'email':'Email',
      'password': 'Password',
      'forgot-password':'Forgot Password',
      'login': 'Login',
      'register': 'Register',
      'new-user': 'I am a new User',
      'invalid-credentials': "Invalid credentials",
      'login-successful': "Login Successful",
      'register-successful': "Registered Successful ",
      'already-user': 'I have an Account ',
      'app-title':'Mfunzi App',
      'sign-up-account':'Sign up a new Account',
      'upload-image':"Upload image",
      'change-lang':'Change Language',
      'confirm':"Confirm Password",
      'welcome-message':"Welcome to Mfunzi",
      'campus':"Mzumbe campus",
      'academic-life':"Academic Life",
      'help-desk':"Help Desk",
      'null-image':"Upload Image",
      'username':"Username:  ",
      'bio':"Bio: ",
      'profile':"Profile",
      'logout':" Logout",
      'edit-profile':"Edit Profile ",
      'share-app':"Share with friends",
      'forum':"Forum",
      'grp':"GRP",
      'multimedia':"Multimedia",
      'resources':"Resources",
      'tools':"Tools",
      'tools-video':"Video",
      'kiunganishi':"and",
      'more-info':"Get to know us Better",
      'visit-site':"Website",
      "other-resources":"Public Files"
    },
    //SWAHILI LANGUAGE
    'sw_TZ':{
      'hello':'Habari',
      'welcome':'Karibu',
      'sign-in':'Ingia ili Kuendelea',
      'create-account':'Fungua Akaunti',
      'sign-up':'Jisajili',
      'sign-up-account':'Sajili akaunti mpya ya Mfunzi',
      'email':'Barua pepe',
      'password': 'Nywila',
      'forgot-password':'Umesahau Nenosiri?',
      'login': ' Ingia',
      'register': ' Jisajili',
      'new-user': 'Mtumiaji mpya? ',
      'already-user': 'Nina akaunti',
      'app-title':'Mfunzi App',
      'change-lang':'Badili Lugha',
      'invalid-credentials': "Taarifa sio sahihi",
      'login-successful': "Umefanikiwa kuingia ",
      'register-successful': "Umefanikiwa kusajili akaunti ",
      'confirm':"Hakiki Nywila",
      'upload-image':"Pakia Picha",
      'welcome-message':"Karibu, Mfunzi",
      'campus':"NDAKI YA MZUMBE",
      'academic-life':"MAISHA YA KITAALUMA",
      'help-desk':"DAWATI LA MSAADA",
      'null-image':"Pakia Picha",
      'username':"Mtumiaji: ",
      'bio':"Wasifu: ",
      'profile':"Wasifu",
      'logout':"Kuondoka",
      'edit-profile':"Badilisha Wasifu",
      'share-app':"Sambaza kwa rafiki",
      'home':"Nyumbani",
      'forum':"Jukwaa",
      'grp':"Dawati",
      'multimedia':"Multimedia",
      'resources':"Hifadhi",
      'tools':"Zana",
      'tools-video':"Video",
      'kiunganishi':"na",
      'more-info':"Pata ujuzi zaidi",
      'visit-site':"Tovuti",
      "other-resources":"Nyaraka za Umma"
    },
  };

}